[theme]
base = "light"

primaryColor = "#E53935"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E3ECF5"
textColor = "#262730"

borderColor = "#04254E"

font = "sans-serif"

baseFontSize = 18
baseFontWeight = 500
metricValueFontWeight = 600

baseRadius = "medium"
showWidgetBorder = true
